### ISSUE TITLE
v0.6.0dev

### ISSUE THREAD

**Issue by Coirt** [Ahornberg/Ahornberg-Microtonal#6]
Hey, @Ahornberg

Forked your plug for v0.6.0dev Win7. Builds okay but crashed when added to rack for the first time.

Want to move onto 0.6.0dev for my own modules, was easier to fork your's than build mine against the master branch. Have a few to do!

Also crashes when deleting multiple modules with a Segmentation fault in the console. If you planned to update yourself don't spoil the fun of figuring it out but there is some comments I added for changes in the API code in the fork. I can post those here if you planned to update yourself.

Thanks again for the PM on RT!

**Comment by Ahornberg** [comment]
Thank you @Court

I will implement the changes for v0.6.0 when it is released.

**Comment by Coirt** [comment]
Your welcome.
