### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by suhr** [Ahornberg/Ahornberg-Microtonal#7]
```
src/EqualDivision.cpp: In constructor 'EqualDivisionWidget::EqualDivisionWidget()':
src/EqualDivision.cpp:158:42: error: no matching function for call to 'rack::ModuleWidget::ModuleWidget()'
 EqualDivisionWidget::EqualDivisionWidget() {
                                          ^
In file included from ../../include/rack.hpp:9:0,
                 from src/Ahornberg.hpp:1,
                 from src/EqualDivision.cpp:1:
../../include/app.hpp:63:2: note: candidate: rack::ModuleWidget::ModuleWidget(rack::Module*)
  ModuleWidget(Module *module);
  ^
../../include/app.hpp:63:2: note:   candidate expects 1 argument, 0 provided
../../include/app.hpp:53:8: note: candidate: rack::ModuleWidget::ModuleWidget(const rack::ModuleWidget&)
 struct ModuleWidget : OpaqueWidget {
        ^
../../include/app.hpp:53:8: note:   candidate expects 1 argument, 0 provided
src/EqualDivision.cpp:179:18: error: 'setModule' was not declared in this scope
  setModule(module);
```

UPDATE: it doesn't happen with v0.5 branch of VCV Rack. Maybe add a note to the README?

**Comment by caecos** [comment]
Same here, won't build on Windows...

**Comment by Martonius** [comment]
I managed to get it to build and work on Windows 7. Had to fix some deprecated code, and a couple other things... as i'm not any kind of expert coder, this took a while. I'm also not sure how to submit fixed code.

**Comment by caecos** [comment]
Can you provide the binary???

**Comment by caecos** [comment]
Can you provide the binary ??



Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Marty Carlton <notifications@github.com>
Envoyé : Tuesday, June 26, 2018 3:23:36 PM
À : Ahornberg/Ahornberg-Microtonal
Cc : caecos; Comment
Objet : Re: [Ahornberg/Ahornberg-Microtonal] Build fails (#7)


I managed to get it to build and work on Windows 7. Had to fix some deprecated code, and a couple other things... as i'm not any kind of expert coder, this took a while. I'm also not sure how to submit fixed code.
